# Generated by Django 4.2.21 on 2025-05-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('comuna_id', models.CharField(max_length=100)),
                ('nom_sucursal', models.CharField(max_length=100)),
                ('direccion_sucursal', models.CharField(max_length=100)),
                ('telefono_sucursal', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id_tipo_user', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_tipo_user', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=100)),
                ('p_apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('correo_user', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('fecha_nac_user', models.DateField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
