# Generated by Django 4.2.21 on 2025-05-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_spacefood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
