# Generated by Django 4.2.21 on 2025-07-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_spacefood', '0002_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('desc_inventario', models.CharField(max_length=100)),
                ('cant_dispo', models.IntegerField(verbose_name='Cantidad disponible')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('desc_marca', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_prod', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=100, verbose_name='Nombre')),
                ('desc_prod', models.CharField(max_length=255, verbose_name='Descripción')),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('fecha_elaboracion', models.DateField(verbose_name='Elaboración')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('inventario', models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app_spacefood.inventario')),
                ('marca', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app_spacefood.marca')),
                ('tipo_producto', models.ForeignKey(db_column='tipo_producto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app_spacefood.tipoproducto')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
    ]
