# Generated by Django 4.2.21 on 2025-07-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_spacefood', '0003_inventario_marca_tipoproducto_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
