# Generated by Django 4.2.21 on 2025-07-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_spacefood', '0004_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={},
        ),
    ]
