# Generated by Django 4.2.21 on 2025-07-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spacefood', '0006_alter_tipoproducto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.IntegerField(default=1, null=True)),
            ],
            options={
                'db_table': 'producto_inventario',
                'managed': False,
            },
        ),
    ]
