# Generated by Django 4.2.21 on 2025-07-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spacefood', '0007_productoinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('region_id', models.IntegerField()),
                ('desc_comuna', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
    ]
